name: nappio-backend
services:
  - name: web
    environment_slug: docker
    dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
    envs:
      - key: PYTHONPATH
        value: /app
      - key: EMAIL_API_TOKEN_TEST
        scope: RUN_TIME
        type: SECRET
      - key: SUPABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: SUPABASE_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SERVICE_NAME
        value: Nappio
      - key: FRONTEND_URL
        value: https://nappio-dev.netlify.app/